### ISSUE TITLE
Remove API keys

### ISSUE THREAD

**Issue by PrzemyslawMalolepszy-TomTom** [NielsMartensGitH/EVOnTheGo#1]
For security reasons it is good not to keep API keys in public repositories.
I'd suggest to remove them from the repo and rotate them.

https://github.com/NielsMartensGitH/EVOnTheGo/blob/92497441b6574ba294e0ee6a6bf22191a8df24ba/assets/javascript/app.js#L3

**Comment by NielsMartensGitH** [comment]
Thank you. It is secured now!
